---
    - name: Install apache2 et mysql
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apache2
        - mysql-server
      when: "'gp1' in group_names"

    - name: Install git nginx cowsay
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - git
        - nginx
        - cowsay
      when: "'gp2' in group_names"

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install
      ansible.builtin.apt:
        name: "ufw"
        state: present
        update_cache: true
      when: "'Ubuntu' == ansible_facts['distribution']"

    - name: Change html file
      ansible.builtin.template:
        src: "index.html"
        dest: /var/www/html/index.html
        mode: "0644"
      when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

    - name: "Get the current day"
      ansible.builtin.set_fact:
        day: "{{ lookup('pipe', 'date +%d') | int }}"

    - name: "Get the current hour"
      ansible.builtin.set_fact:
        hour: "{{ lookup('pipe', 'date +%H') | int }}"

    - name: Change jour
      ansible.builtin.template:
        src: "jour.j2"
        dest: /etc/jour
        mode: "0644"
